### ISSUE TITLE
Can't return Tuple responses when CORS is enabled

### ISSUE THREAD

**Issue by alissonpelizaro** [goblet/goblet#490]
Hi @anovis , how are you doing?

We are getting an error when we return a `Tuple` type response in a Route with CORS enabled in the app. For example:

```python
from goblet import Goblet

app = Goblet(function_name='helloworld',
             cors=True)

@app.route('/test')
def index():
    return {'view': 'index'}, 201
```

This code raises `IndexError: tuple index out of range`.

Disabling CORS make this code run as expected:
```python
from goblet import Goblet

app = Goblet(function_name='helloworld')

@app.route('/test')
def index():
    return {'view': 'index'}, 201
```

The full traceback is:
```
Traceback (most recent call last):
  File "/Users/alisson/webprojects/goblet-test/.direnv/python-3.11.6/lib/python3.11/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alisson/webprojects/goblet-test/.direnv/python-3.11.6/lib/python3.11/site-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alisson/webprojects/goblet-test/.direnv/python-3.11.6/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alisson/webprojects/goblet-test/.direnv/python-3.11.6/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alisson/webprojects/goblet-test/.direnv/python-3.11.6/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alisson/webprojects/goblet-test/.direnv/python-3.11.6/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alisson/webprojects/goblet-test/.direnv/python-3.11.6/lib/python3.11/site-packages/functions_framework/__init__.py", line 134, in view_func
    return function(request._get_current_object())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alisson/webprojects/goblet-test/.direnv/python-3.11.6/lib/python3.11/site-packages/goblet/app.py", line 66, in local_func
    return self(request)
           ^^^^^^^^^^^^^
  File "/Users/alisson/webprojects/goblet-test/.direnv/python-3.11.6/lib/python3.11/site-packages/goblet/resource_manager.py", line 189, in __call__
    raise e
  File "/Users/alisson/webprojects/goblet-test/.direnv/python-3.11.6/lib/python3.11/site-packages/goblet/resource_manager.py", line 169, in __call__
    response = self.handlers["route"](request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alisson/webprojects/goblet-test/.direnv/python-3.11.6/lib/python3.11/site-packages/goblet/handlers/routes.py", line 103, in __call__
    return entry(request)
           ^^^^^^^^^^^^^^
  File "/Users/alisson/webprojects/goblet-test/.direnv/python-3.11.6/lib/python3.11/site-packages/goblet/handlers/routes.py", line 432, in __call__
    return self._apply_cors(resp)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alisson/webprojects/goblet-test/.direnv/python-3.11.6/lib/python3.11/site-packages/goblet/handlers/routes.py", line 453, in _apply_cors
    resp[2].update(self.cors.get_access_control_headers())
IndexError: tuple index out of range
```

Is this the expected behavior? We are using some libraries based on Flask that run well with Goblet... but when these external libraries return a Tuple response, we face this issue.

**Comment by anovis** [comment]
right now it looks like [goblet](https://github.com/goblet/goblet/blob/main/goblet/handlers/routes.py#L453) is expecting a dictionary of headers for the 3rd argument if a touple is returned with cors, which is based off of the [Flask response object](https://flask.palletsprojects.com/en/3.0.x/api/#response-objects). 

if you return ` {'view': 'index'}, 201, {}` does that fix it? 

ill take a look more in depth later this week.

**Comment by alissonpelizaro** [comment]
Yes, it does. Setting `{}` as third argument the problem disappear.

```python
from goblet import Goblet

app = Goblet(function_name='helloworld',
             cors=True)

@app.route('/test')
def index():
    return {'view': 'index'}, 201, {}
```

For now, I will intercept the responses from the external libraries to inject this `{}` as an alternative solution. 
Thank you @anovis.

**Comment by anovis** [comment]
@alissonpelizaro I am glad that worked. In the meantime I'll work on a fix for it

**Comment by alissonpelizaro** [comment]
Something like this must fix:


```python
# goblet/handlers/routes.py:445

    def _apply_cors(self, resp):
        """Apply cors to Response"""
        if not self.cors:
            return resp
        # Apply to Response Obj
        if isinstance(resp, goblet.Response):
            resp.headers.update(self.cors.get_access_control_headers())
        if isinstance(resp, tuple):
            # Flask custom Tuple response: body, status code, headers ({}, 200, {})
            if len(resp) > 2:
                resp[2].update(self.cors.get_access_control_headers())
            else:
                resp = goblet.Response(
                    resp[0],
                    status_code=int(resp[1]) or 200, 
                    headers=self.cors.get_access_control_headers()
                )
        if isinstance(resp, str):
            resp = goblet.Response(resp, headers=self.cors.get_access_control_headers())
        return resp
```

In my tests, it works. I can submit a PR if you want.

**Comment by anovis** [comment]
awesome @alissonpelizaro. that looks good. feel free to add a pr and i can include it in the next release this weekend. 

it would be nice if you added a test case as well with this, so we can ensure it works in the future as well!

**Comment by alissonpelizaro** [comment]
Certainly, here's the PR:
https://github.com/goblet/goblet/pull/491
